image:
  file: .ContainerFile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'
tasks:
  - name: Set up Git Config
    openIn: bottom
    command: git config --global user.name "jortfal" &&
             git config --global user.email "jortfal@users.noreply.github.com" &&
             git config --global commit.gpgsign true &&
             git config --global user.signingkey 0000000000000000 &&
             touch private.gpg &&
             echo 'WARNING!!! Do not forget to import the private gpg key ;)' &&
             echo 'use "gpg --import private.gpg" to import private key '
vscode:
  "shd101wyy.markdown-preview-enhanced",
  "yzhang.markdown-all-in-one",
  "DavidAnson.vscode-markdownlint"
