name: Test

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - hotfix/*

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    strategy:
      matrix:
        node-version: # Node.js Releases https://nodejs.org/en/about/previous-releases#nodejs-releases
          - 10.24.1  # LTS Unsupported
          - 11.15.0  # --- Unsupported
          - 12.22.12 # LTS Unsupported
          - 13.14.0  # --- Unsupported
          - 14.21.3  # LTS Unsupported
          - 15.14.0  # --- Unsupported
          - 16.20.2  # LTS Unsupported
          - 17.9.1   # --- Unsupported
          - 18.20.3  # LTS Maintenance
          - 19.9.0   # --- Unsupported
          - 20.14.0  # LTS Active
          - 21       # Current
          - 22       # Current

    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - run: git config --global user.name github-actions
        - run: git config --global user.email github-actions@github.com
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
        - name: Ensure dependencies are compatible with the version of node
          run: echo 'engine-strict=true' >> .npmrc
        - name: Setup NPM
          uses: bahmutov/npm-install@v1
        - name: Run tests
          run: npm run test
